export const MEDIA_INITIAL_LIMIT = 9;
export const IMAGE_CACHE_LIMIT = 9;
export const MEDIA_LOAD_STEP = 9;
export const MEDIA_MAX_LIMIT = 100;
export const LIGHTBOX_ANIMATION_MS = 180;

export const VIDEO_MUTED_STORAGE_KEY = "daily_sharing_dashboard_video_muted";
export const VIDEO_CONTROLS_HIDE_DELAY_MS = 0;
export const VIDEO_CONTROLS_REVEAL_HIDE_DELAY_MS = 520;
export const VIDEO_CONTROLS_TOUCH_REVEAL_HIDE_DELAY_MS = 9000;
export const VIDEO_CONTROLS_TOUCH_SEEK_HIDE_DELAY_MS = 1400;
export const VIDEO_CONTROLS_LEAVE_HIDE_DELAY_MS = VIDEO_CONTROLS_HIDE_DELAY_MS;
export const VIDEO_CONTROLS_REVEAL_PADDING = 36;
