import { MEDIA_INITIAL_LIMIT } from "./constants.js?v=20260609-media-flat";

export function createDashboardState() {
  return {
    activeView: "dashboard",
    status: null,
    configData: null,
    configDirty: false,
    configApplying: false,
    configSaving: false,
    configAutoSaveTimer: 0,
    configSaveQueued: false,
    configChangeSeq: 0,
    settingsTab: "target",
    media: [],
    mediaLoaded: false,
    mediaLimit: MEDIA_INITIAL_LIMIT,
    mediaHasMore: true,
    mediaLoading: false,
    mediaRequestSeq: 0,
    mediaRenderSignature: "",
    mediaKindFilter: "all",
    mediaTypeFilter: "all",
    mediaLightboxToken: 0,
    mediaLightboxItem: null,
    mediaLightboxPreviewUrl: "",
    mediaLightboxViewSource: null,
    mediaLightboxViewPromise: null,
    mediaLightboxViewLoading: false,
    mediaLightboxViewLoaded: false,
    mediaImageCache: new Map(),
    overlayLockCount: 0,
    overlayScrollY: 0,
    overlayTouchY: 0,
    mediaLightboxCloseTimer: 0,
    mediaLightboxControlTimer: 0,
    mediaLightboxSuppressCloseClick: false,
    mediaLightboxSuppressCloseTimer: 0,
    mediaLightboxControlsRevealLocked: false,
    mediaLightboxControlsHotzoneSuppressed: false,
    mediaLightboxControlsLeaveDirection: "",
    mediaLightboxControlsPointerY: null,
    mediaLightboxProgressDragging: false,
    mediaLightboxProgressPointerId: null,
    textLightboxCloseTimer: 0,
    targetTab: "share",
    targetsDirty: false,
    targetCarouselIndex: 0,
    targetCarouselSignature: "",
    targetCarouselTimer: 0,
    pollTimer: 0,
    noticeTimer: 0,
    calendarPageIndex: 0,
    calendarPageCount: 0,
    calendarCarouselTimer: 0,
    calendarSignature: "",
    calendarLayoutFrame: 0,
    calendarLayoutNeedsRender: false,
    calendarStableListHeight: 0,
    calendarResizeObserver: null,
    sakuraEnabled: true,
    sakuraSaving: false,
    sakuraSynced: false,
    sakuraToggleBound: false,
    pageSwitchBound: false,
    activeViewSyncedFromServer: false,
    activeViewSaving: false,
    activeViewSaveSeq: 0,
    settingsScrollFrame: 0,
    settingsScrollLockUntil: 0,
    watchedRuns: new Map(),
    bridgeReady: false,
  };
}
